AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository (Docker images)
## Docs : https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/template-reference.html

############################################################
###                    Parameters                        ###
Parameters:
  ParamEcrRepoName:
    Description: 'ECR repository name'
    Type: String

############################################################
###                     Resources                        ###
Resources:

  ###         ECR Repository            ###
  # Amazon Elastic Container Registry (Amazon ECR) repository, where users can push and pull Docker images.
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ParamEcrRepoName

############################################################
###                       Outputs                        ###
Outputs:

  RepositoryName:
    Value: !Ref EcrRepository
    Export:
      Name: 'RepositoryName'

  RepositoryDNS:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"
    Export:
      Name: 'RepositoryDNS'

  RepositoryArn:
    Value: !GetAtt EcrRepository.Arn
    Export:
      Name: 'RepositoryArn'

